version: "3"

volumes:
      produtosdata:

networks:
       frontend:
       backend:

services:

      mysql:
        image: "mysql:5.7"
        restart: always
        volumes:
          - produtosdata:/var/lib/mysql
          - ./_MYSQL_INIT_SCRIPT:/docker-entrypoint-initdb.d
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=numsey
          #- bind-address=0.0.0.0
        ports:
      # <Port exposed> : < MySQL Port running inside container>
          - '3306:3306'
        expose:
      # Opens port 3306 on the container
          - '3306'

      mvc:
        build:
          context: .
          dockerfile: Dockerfile
        networks:
          - backend
          - frontend
        ports:
          - 5000:80
        environment:
          - DBHOST=mysql
        depends_on:
          - mysql
            